jwt:
  secret: 'jwt-secret'

spring:
  datasource:
    url: jdbc:postgresql://localhost/hotel_booking_application
    username: postgres
    password: password
  jpa:
    show-sql : false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
