jwt:
  secret: 'jwt-secret'

spring:
  datasource:
    url: jdbc:postgresql://database:5432/hotel_booking_application
    username: postgres
    password: password
  jpa:
    show-sql : false
    hibernate:
      ddl-auto: create
