version: "3.8"

services:

  database:
    image: postgres:alpine
    container_name: database-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hotel_booking_application

  backend:
    build: ./BACKEND-APPLICATION
    image: backend-image
    container_name: backend-container
    ports:
      - "8081:8080"
    environment:
      DB_URL: jdbc:postgresql://database:5432/hotel_booking_application
    depends_on:
      - database

  frontend:
    build: ./FRONTEND-APPLICATION
    image: frontend-image
    container_name: frontend-container
    ports:
      - "4200:80"
    depends_on:
      - backend

