version: "3.8"
services:
  frontend:
    build: ./FRONTEND-APPLICATION
    ports:
      - "4200:80"
    depends_on:
      - backend
  backend:
    build: ./BACKEND-APPLICATION
    ports:
      - "8081:8080"
    depends_on:
      - database
    environment:
      DB_URL: jdbc:postgresql://database:5432/hotel_booking_application
  database:
    image: postgres:alpine
    environment:
      POSTGRES_DB: hotel_booking_application
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
