version: "3.8"
services:
  frontend:
    build: ./FRONTEND-APPLICATION
    ports:
      - "4200:4200"
  backend:
    build: ./BACKEND-APPLICATION
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://localhost:5432/hotel_booking_application
  database:
    image: postgres:alpine
    environment:
      POSTGRES_DB: hotel_booking_application
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"